### PR TITLE
recalculate txns list length + hide errant li on init

### LINKED ISSUE #293: Application error: a client-side exception has occurred after clicking please log in.
**Env:**
OS - Win 10
Browser - Chrome Version 115.0.5790.110
**Summary:**
IF user opens FAQ page and go back to main site. Clicking "please log in" in Transaction section, causes "Application error: a client-side exception"
image
image
**Preconditions:**
Refresh the site so login popup is not visible
**Steps to reproduce:**
1. When login popup is not visible click on ? icon to open external page with FAQ
2. Go back to main page
3. Click on "please log in" in "Transactions" section
4. Observe

### PR DESCRIPTION
**Pull request by Syncretik**
- hide "Show All Transactions" <li> on init
- force close on login to prevent race condition when fetching and calculating transaction list height.

resolves #293

### CODE REVIEW

File: components/Transactions.tsx [hunk 1]
```diff
@@ -19,8 +19,13 @@ export default function Transactions() {
 
   const [isOpen, toggleOpen] = useCycle(false, true);
 
+  useEffect(() => {
+    // force close to avoid race condition with fetching transfers
+    toggleOpen(0);
```
Comment (Riglanto) [inline components/Transactions.tsx:24]: Why 0 not false? :p

**Review by Riglanto — APPROVED** [review]

File: components/Transactions.tsx (hunk 1 above)
Comment (Syncretik) [reply components/Transactions.tsx:24]: 0 is the index of the cycle :)

Comment (Riglanto) [reply components/Transactions.tsx:24]: lol nice
